service: location-service

provider:
  name: aws
  runtime: nodejs18.x
  vpc:
    securityGroupIds:
      - ${ssm:/location-service/security-group-id}
    subnetIds:
      - ${ssm:/location-service/subnet-id}
  # environment:
  #   NODE_ENV: production
  #   PORT: 3000
  #   DB_HOST: ${env:DB_HOST}
  #   DB_PORT: 5432
  #   DB_USER: ${env:DB_USER}
  #   DB_PASS: ${env:DB_PASSWORD}
  #   DB_NAME: ${env:DB_NAME}
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  region: us-west-2
  stage: dev

functions:
  app:
    handler: src/index.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: "{proxy+}"
          method: any

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
